import type { AgentInputDefinition } from "./agentEmbedProtocol";

const js = (value: unknown) => JSON.stringify(value, null, 2).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
const examples: Record<string, unknown> = { string: "Replace with your value", number: 0, integer: 0, boolean: false,
    date: "2026-01-01", datetime: "2026-01-01T09:00:00Z", object: {}, array: [] };

export function embedSamples(agentId: number, fields: AgentInputDefinition[], sdkUrl: string, hubBase: string) {
    const values = Object.fromEntries(fields.map((field) => [field.name, examples[field.dataType] ?? "Replace with your value"]));
    const config = `agentId: ${agentId},\n    tokenEndpoint: "/api/agent-chat/token",\n    inputs: ${js(values).replace(/\n/g, "\n    ")}`;
    return {
        javascript: `<div id="agent-chat"></div>\n<script src=${JSON.stringify(sdkUrl).replace(/</g, "&lt;")}></script>\n<script>\n  // Replace the sample input values with values from your application.\n  const chat = SolidAgentEmbed.mount({\n    container: "#agent-chat",\n    ${config}\n  });\n  // chat.open(); chat.close();\n  // await chat.setInputs({ ... }); // Before the first message or after New chat.\n  // chat.destroy(); // When removing this integration.\n</script>`,
        react: `import { useEffect, useRef } from "react";\n\n// No SolidX npm dependency. The hosted SDK is shared by JavaScript and React.\nlet sdkPromise;\nfunction loadSdk() {\n  if (window.SolidAgentEmbed) return Promise.resolve(window.SolidAgentEmbed);\n  if (!sdkPromise) {\n    sdkPromise = new Promise((resolve, reject) => {\n      const script = document.createElement("script");\n      script.src = ${js(sdkUrl)};\n      script.onload = () => resolve(window.SolidAgentEmbed);\n      script.onerror = () => { script.remove(); sdkPromise = null; reject(new Error("Could not load the chat SDK")); };\n      document.head.appendChild(script);\n    });\n  }\n  return sdkPromise;\n}\n\nexport default function AgentChat() {\n  const container = useRef(null);\n  useEffect(() => {\n    let disposed = false;\n    let chat;\n    loadSdk().then((sdk) => {\n      if (disposed) return;\n      chat = sdk.mount({\n        container: container.current,\n        ${config.replace(/\n/g, "\n    ")}\n      });\n    }).catch((error) => { if (!disposed) console.error(error.message); });\n    return () => { disposed = true; chat?.destroy(); };\n  }, []);\n  return <div ref={container} />;\n}`,
        express: `// Add this to your authenticated Express application.\n// Dependencies: express, express-rate-limit (Node.js 20+ for fetch).\n// Set SOLIDX_API_KEY on the server only:\n// SOLIDX_API_KEY=sldx_13212xxxxxx  # API key goes here\nimport express from "express";\nimport { rateLimit } from "express-rate-limit";\n\nconst router = express.Router();\nrouter.post("/api/agent-chat/token",\n  (req, res, next) => {\n    res.set("Cache-Control", "no-store");\n    // Your existing authentication middleware must populate req.user.\n    if (!req.user?.id) return res.sendStatus(401);\n    if (!req.user.permissions?.includes("agent:chat")) return res.sendStatus(403);\n    next();\n  },\n  rateLimit({ windowMs: 60_000, limit: 20 }),\n  async (req, res) => {\n    try {\n      const upstream = await fetch(${js(`${hubBase.replace(/\/$/, "")}/api/agent/api-keys/embedded/me`)}, {\n        method: "POST",\n        headers: { "Content-Type": "application/json" },\n        body: JSON.stringify({\n          apiKey: process.env.SOLIDX_API_KEY,\n          agentId: ${agentId}, // Authorize this agent on your server; ignore browser-supplied IDs.\n          ...(req.user?.id != null ? { externalUserId: "my-app:" + req.user.id } : {})\n        }),\n        signal: AbortSignal.timeout(15_000)\n      });\n      if (!upstream.ok) return res.status(502).json({ error: "Chat is temporarily unavailable" });\n      res.json(await upstream.json());\n    } catch { res.status(503).json({ error: "Chat is temporarily unavailable" }); }\n  }\n);\nexport default router;\n// Mount after your authentication and CSRF middleware. Configure trusted proxies\n// correctly if deployed behind a load balancer. Map agent:chat to your access policy.`,
        java: `// Spring Boot 3 / Java 17+. Enable method security and configure authentication.\n// Uses Spring Security and Resilience4j's Spring Boot rate limiter integration.\n// Server environment: SOLIDX_API_KEY=sldx_13212xxxxxx  // API key goes here\n@RestController\npublic class AgentEmbedController {\n  private final java.net.http.HttpClient client = java.net.http.HttpClient.newHttpClient();\n  private final com.fasterxml.jackson.databind.ObjectMapper json = new com.fasterxml.jackson.databind.ObjectMapper();\n\n  @PostMapping("/api/agent-chat/token")\n  @org.springframework.security.access.prepost.PreAuthorize("hasAuthority('agent:chat')")\n  @io.github.resilience4j.ratelimiter.annotation.RateLimiter(name = "agentEmbed")\n  public ResponseEntity<String> token(java.security.Principal principal) {\n    try {\n      String body = json.writeValueAsString(java.util.Map.of(\n        "apiKey", System.getenv("SOLIDX_API_KEY"),\n        "agentId", ${agentId},\n        "externalUserId", "my-app:" + principal.getName()));\n      var request = java.net.http.HttpRequest.newBuilder()\n        .uri(java.net.URI.create(${js(`${hubBase.replace(/\/$/, "")}/api/agent/api-keys/embedded/me`)}))\n        .timeout(java.time.Duration.ofSeconds(15))\n        .header("Content-Type", "application/json")\n        .POST(java.net.http.HttpRequest.BodyPublishers.ofString(body)).build();\n      var response = client.send(request, java.net.http.HttpResponse.BodyHandlers.ofString());\n      if (response.statusCode() != 200) return ResponseEntity.status(502).cacheControl(CacheControl.noStore()).build();\n      return ResponseEntity.ok().cacheControl(CacheControl.noStore())\n        .contentType(MediaType.APPLICATION_JSON).body(response.body());\n    } catch (Exception error) {\n      return ResponseEntity.status(503).cacheControl(CacheControl.noStore()).build();\n    }\n  }\n}\n// Imports: org.springframework.web.bind.annotation.*, org.springframework.http.*.\n// Configure agentEmbed: limitForPeriod=20, limitRefreshPeriod=60s, timeoutDuration=0.\n// Keep your application's CSRF protection and supply its header using getTokenHeaders.`,
        dotnet: `// ASP.NET Core 8+. Add to your application's existing authentication setup.\n// Server environment: SOLIDX_API_KEY=sldx_13212xxxxxx  // API key goes here\nbuilder.Services.AddHttpClient("AgentHub", client => client.Timeout = TimeSpan.FromSeconds(15));\nbuilder.Services.AddAuthorization(options => options.AddPolicy("AgentChat", policy =>\n    policy.RequireAuthenticatedUser().RequireClaim("permission", "agent:chat")));\nbuilder.Services.AddRateLimiter(options => {\n    options.RejectionStatusCode = 429;\n    options.AddPolicy("agent-embed", context =>\n        System.Threading.RateLimiting.RateLimitPartition.GetFixedWindowLimiter(\n            context.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value ?? "anonymous",\n            _ => new System.Threading.RateLimiting.FixedWindowRateLimiterOptions {\n                PermitLimit = 20, Window = TimeSpan.FromMinutes(1), QueueLimit = 0\n            }));\n});\n// After building app: UseAuthentication(), UseAuthorization(), UseRateLimiter().\napp.MapPost("/api/agent-chat/token", async (HttpContext context, IHttpClientFactory clients) => {\n    context.Response.Headers.CacheControl = "no-store";\n    var subject = context.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;\n    if (string.IsNullOrEmpty(subject)) return Results.Unauthorized();\n    try {\n        var upstream = await clients.CreateClient("AgentHub").PostAsJsonAsync(\n            ${js(`${hubBase.replace(/\/$/, "")}/api/agent/api-keys/embedded/me`)}, new {\n                apiKey = Environment.GetEnvironmentVariable("SOLIDX_API_KEY"),\n                agentId = ${agentId}, externalUserId = "my-app:" + subject\n            }, context.RequestAborted);\n        if (!upstream.IsSuccessStatusCode) return Results.StatusCode(502);\n        return Results.Text(await upstream.Content.ReadAsStringAsync(), "application/json");\n    } catch { return Results.StatusCode(503); }\n}).RequireAuthorization("AgentChat").RequireRateLimiting("agent-embed");\n// Retain your application's CSRF protection when using cookie authentication.`,
    };
}
