import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQueryWithAuth } from "./fetchBaseQuery";

export type DatasourceIntrospectionBootstrap = {
  module: {
    id: number;
    name: string;
    displayName: string;
    description: string;
    defaultDataSource: string;
  };
  datasources: Array<{
    name: string;
    displayName: string;
    type: string;
    envPrefix: string;
    isDefault: boolean;
    synchronize: boolean | null;
    host: string;
    port: number | null;
    database: string;
  }>;
  recommendedDatasourceName: string | null;
};

export type DatasourceIntrospectionTableRecord = {
  schema: string | null;
  tableName: string;
  mapped: boolean;
  mappedModelId: number | null;
  mappedModelSingularName: string | null;
  mappedModelDisplayName: string | null;
  mappedModuleId: number | null;
  mappedModuleName: string | null;
  mappedModuleDisplayName: string | null;
  suggestedLegacyTableType: "none" | "existing_id" | "generated_id";
  suggestedBaseClassName: string;
  suggestedIdColumnName: string | null;
  suggestedUserKeyField: string;
  columnCount: number;
  physicalColumnCount: number;
};

export type DatasourceIntrospectionTablesResponse = {
  module: DatasourceIntrospectionBootstrap["module"];
  datasource: DatasourceIntrospectionBootstrap["datasources"][number];
  synchronizeBlocked: boolean;
  synchronizeMessage: string | null;
  records: DatasourceIntrospectionTableRecord[];
  meta: {
    totalRecords: number;
  };
};

export type DatasourceIntrospectionTableDetail = {
  module: DatasourceIntrospectionBootstrap["module"];
  datasource: DatasourceIntrospectionBootstrap["datasources"][number];
  table: DatasourceIntrospectionTableRecord;
  columns: Array<{
    columnName: string;
    fieldName: string;
    displayName: string;
    dataType: string;
    solidFieldType: string;
    ormType: string;
    nullable: boolean;
    defaultValue: string | null;
    characterMaximumLength: number | null;
    numericPrecision: number | null;
    numericScale: number | null;
    ordinalPosition: number | null;
    isAutoGenerated: boolean;
    isPrimaryKey: boolean;
    handledBySuperclass: boolean;
    superclassFieldName: string | null;
  }>;
  rawDdl: {
    statement: string | null;
    available: boolean;
    note: string | null;
  };
  userKeyCandidates: Array<{
    name: string;
    label: string;
    score: number;
    reason: string;
    isDefault: boolean;
  }>;
  suggestedMetadata: {
    singularName: string;
    pluralName: string;
    displayName: string;
    tableName: string;
    schema: string | null;
    dataSource: string;
    dataSourceType: string;
    legacyTableType: "none" | "existing_id" | "generated_id";
    baseClassName: string;
    userKeyField: string;
    synchronize: false;
  };
};

export type DatasourceIntrospectionMappingColumn = {
  columnName: string;
  fieldName: string;
  displayName: string;
  dataType: string;
  solidFieldType: string;
  ormType: string;
  nullable: boolean;
  defaultValue: string | null;
  characterMaximumLength: number | null;
  numericPrecision: number | null;
  numericScale: number | null;
  ordinalPosition: number | null;
  isAutoGenerated: boolean;
  handledBySuperclass: boolean;
  superclassFieldName: string | null;
  fieldId: number | null;
  include: boolean;
  matched: boolean;
  isPrimaryKey: boolean;
};

export type DatasourceIntrospectionMappingRequest = {
  mapped: boolean;
  modelId: number | null;
  singularName: string;
  pluralName: string;
  displayName: string;
  description: string;
  tableName: string;
  schema: string | null;
  dataSource: string;
  dataSourceType: string;
  legacyTableType: "none" | "existing_id" | "generated_id";
  baseClassName: string;
  userKeyField: string;
  enableAuditTracking: boolean;
  enableSoftDelete: boolean;
  draftPublishWorkflow: boolean;
  internationalisation: boolean;
  plannedMigrationTimestamp?: number | null;
  columns: DatasourceIntrospectionMappingColumn[];
  reviewedModel?: Record<string, any>;
};

export type DatasourceIntrospectionMappingPreview = {
  operation: "create" | "update";
  mappedModelId: number | null;
  metadataJson: {
    filePath: string;
    model: Record<string, any>;
  };
  migration: {
    willGenerate: boolean;
    filePath: string | null;
    fileName: string | null;
    className: string | null;
    timestamp: number | null;
    content: string | null;
    note: string;
    missingSystemColumns: string[];
  };
  summary: {
    includedColumnNames: string[];
    removedColumnNames: string[];
    missingSystemColumns: string[];
    generatedSystemColumnCount: number;
  };
};

export type DatasourceIntrospectionApplyResponse = DatasourceIntrospectionMappingPreview & {
  modelId: number | null;
};

export type DatasourceIntrospectionCreateMigrationResponse = {
  modelId: number | null;
  operation: "create" | "update";
  datasourceFile: {
    filePath: string;
    created: boolean;
    updated: boolean;
    entityRegistered: boolean;
    migrationGlobRegistered: boolean;
  };
  migration: DatasourceIntrospectionMappingPreview["migration"] & {
    written: boolean;
  };
  summary: DatasourceIntrospectionMappingPreview["summary"];
};

export type DatasourceIntrospectionCommandResponse = {
  moduleId: number;
  datasource?: string;
  command?: string;
  output: string;
  message: string;
};

function unwrapEnvelope<T = any>(payload: any): T {
  let current = payload;

  while (
    current
    && typeof current === "object"
    && "data" in current
    && current.data !== undefined
  ) {
    current = current.data;
  }

  return current as T;
}

export const datasourceIntrospectionApi = createApi({
  reducerPath: "datasourceIntrospectionApi",
  baseQuery: baseQueryWithAuth,
  tagTypes: ["DatasourceIntrospection"],
  endpoints: (builder) => ({
    getDatasourceIntrospectionBootstrap: builder.query<DatasourceIntrospectionBootstrap, number>({
      query: (moduleId) => `/datasource-introspection/modules/${moduleId}/bootstrap`,
      providesTags: ["DatasourceIntrospection"],
      transformResponse: (response: any) => unwrapEnvelope<DatasourceIntrospectionBootstrap>(response),
    }),
    getDatasourceIntrospectionTables: builder.query<
      DatasourceIntrospectionTablesResponse,
      { moduleId: number; datasource: string }
    >({
      query: ({ moduleId, datasource }) =>
        `/datasource-introspection/modules/${moduleId}/tables?datasource=${encodeURIComponent(datasource)}`,
      providesTags: ["DatasourceIntrospection"],
      transformResponse: (response: any) => unwrapEnvelope<DatasourceIntrospectionTablesResponse>(response),
    }),
    getDatasourceIntrospectionTableDetail: builder.query<
      DatasourceIntrospectionTableDetail,
      { moduleId: number; datasource: string; table: string; schema?: string | null }
    >({
      query: ({ moduleId, datasource, table, schema }) => {
        const searchParams = new URLSearchParams();
        searchParams.set("datasource", datasource);
        searchParams.set("table", table);
        if (schema) {
          searchParams.set("schema", schema);
        }

        return `/datasource-introspection/modules/${moduleId}/table-detail?${searchParams.toString()}`;
      },
      providesTags: ["DatasourceIntrospection"],
      transformResponse: (response: any) => unwrapEnvelope<DatasourceIntrospectionTableDetail>(response),
    }),
    previewDatasourceIntrospectionMapping: builder.mutation<
      DatasourceIntrospectionMappingPreview,
      { moduleId: number; payload: DatasourceIntrospectionMappingRequest }
    >({
      query: ({ moduleId, payload }) => ({
        url: `/datasource-introspection/modules/${moduleId}/mapping-preview`,
        method: "POST",
        body: payload,
      }),
      transformResponse: (response: any) => unwrapEnvelope<DatasourceIntrospectionMappingPreview>(response),
    }),
    applyDatasourceIntrospectionMapping: builder.mutation<
      DatasourceIntrospectionApplyResponse,
      { moduleId: number; payload: DatasourceIntrospectionMappingRequest }
    >({
      query: ({ moduleId, payload }) => ({
        url: `/datasource-introspection/modules/${moduleId}/apply-mapping`,
        method: "POST",
        body: payload,
      }),
      invalidatesTags: ["DatasourceIntrospection"],
      transformResponse: (response: any) => unwrapEnvelope<DatasourceIntrospectionApplyResponse>(response),
    }),
    createDatasourceIntrospectionMigrationArtifacts: builder.mutation<
      DatasourceIntrospectionCreateMigrationResponse,
      { moduleId: number; payload: DatasourceIntrospectionMappingRequest }
    >({
      query: ({ moduleId, payload }) => ({
        url: `/datasource-introspection/modules/${moduleId}/create-migration-artifacts`,
        method: "POST",
        body: payload,
      }),
      invalidatesTags: ["DatasourceIntrospection"],
      transformResponse: (response: any) => unwrapEnvelope<DatasourceIntrospectionCreateMigrationResponse>(response),
    }),
    generateDatasourceIntrospectionCode: builder.mutation<
      DatasourceIntrospectionCommandResponse,
      { moduleId: number }
    >({
      query: ({ moduleId }) => ({
        url: `/datasource-introspection/modules/${moduleId}/generate-code`,
        method: "POST",
      }),
      transformResponse: (response: any) => unwrapEnvelope<DatasourceIntrospectionCommandResponse>(response),
    }),
    runDatasourceIntrospectionMigration: builder.mutation<
      DatasourceIntrospectionCommandResponse,
      { moduleId: number; datasource: string }
    >({
      query: ({ moduleId, datasource }) => ({
        url: `/datasource-introspection/modules/${moduleId}/run-migration`,
        method: "POST",
        body: { datasource },
      }),
      transformResponse: (response: any) => unwrapEnvelope<DatasourceIntrospectionCommandResponse>(response),
    }),
  }),
});

export const {
  useGetDatasourceIntrospectionBootstrapQuery,
  useGetDatasourceIntrospectionTablesQuery,
  useGetDatasourceIntrospectionTableDetailQuery,
  usePreviewDatasourceIntrospectionMappingMutation,
  useApplyDatasourceIntrospectionMappingMutation,
  useCreateDatasourceIntrospectionMigrationArtifactsMutation,
  useGenerateDatasourceIntrospectionCodeMutation,
  useRunDatasourceIntrospectionMigrationMutation,
} = datasourceIntrospectionApi;
