import {
  ArrowLeft,
  Check,
  Cog,
  Database,
  ExternalLink,
  RefreshCw,
  Save,
  Search,
  ShieldAlert,
  Sparkles,
} from "lucide-react";
import { camelCase, startCase } from "lodash";
import { useEffect, useMemo, useRef, useState } from "react";
import { useDispatch } from "react-redux";
import { useNavigate, useParams } from "react-router-dom";
import { showToast } from "../../../../redux/features/toastSlice";
import { SolidJsonEditor } from "../../../../components/core/json/SolidJsonEditor";
import { Column, SolidDataTable } from "../../../../components/core/list/SolidDataTable";
import { waitForBackendAvailability } from "../../../../helpers/waitForBackendAvailability";
import {
  SolidButton,
  SolidCheckbox,
  SolidDialog,
  SolidDialogBody,
  SolidDialogClose,
  SolidDialogDescription,
  SolidDialogFooter,
  SolidDialogHeader,
  SolidDialogSeparator,
  SolidDialogTitle,
  SolidInput,
  SolidSelect,
  SolidSpinner,
  SolidSwitch,
  SolidTabGroup,
  SolidTextarea,
} from "../../../../components/shad-cn-ui";
import {
  type DatasourceIntrospectionTableDetail,
  type DatasourceIntrospectionMappingPreview,
  type DatasourceIntrospectionMappingRequest,
  type DatasourceIntrospectionTableRecord,
  type DatasourceIntrospectionApplyResponse,
  type DatasourceIntrospectionCreateMigrationResponse,
  useApplyDatasourceIntrospectionMappingMutation,
  useCreateDatasourceIntrospectionMigrationArtifactsMutation,
  useGenerateDatasourceIntrospectionCodeMutation,
  useGetDatasourceIntrospectionBootstrapQuery,
  useGetDatasourceIntrospectionTableDetailQuery,
  useGetDatasourceIntrospectionTablesQuery,
  usePreviewDatasourceIntrospectionMappingMutation,
  useRunDatasourceIntrospectionMigrationMutation,
} from "../../../../redux/api/datasourceIntrospectionApi";
import { useGetmodelByIdQuery } from "../../../../redux/api/modelApi";
import "./DatasourceIntrospectionPage.css";

type SessionSettings = {
  relationInferenceEnabled: boolean;
  prioritizeUnmappedTables: boolean;
};

type WorkspaceStep =
  | "configure"
  | "review-json"
  | "generate-code"
  | "create-migrations"
  | "run-migration";

type DrawerColumnDraft = {
  columnName: string;
  fieldName: string;
  displayName: string;
  dataType: string;
  solidFieldType: string;
  ormType: string;
  nullable: boolean;
  defaultValue: string | null;
  characterMaximumLength: number | null;
  numericPrecision: number | null;
  numericScale: number | null;
  ordinalPosition: number | null;
  isAutoGenerated: boolean;
  isDetectedPrimaryKey: boolean;
  handledBySuperclass: boolean;
  superclassFieldName: string | null;
  fieldId: number | null;
  include: boolean;
  matched: boolean;
  isPrimaryKey: boolean;
};

type DrawerDraft = {
  mapped: boolean;
  modelId: number | null;
  mappedModuleLabel: string | null;
  singularName: string;
  pluralName: string;
  displayName: string;
  description: string;
  tableName: string;
  schema: string | null;
  dataSource: string;
  dataSourceType: string;
  legacyTableType: "none" | "existing_id" | "generated_id";
  baseClassName: string;
  userKeyField: string;
  enableAuditTracking: boolean;
  enableSoftDelete: boolean;
  draftPublishWorkflow: boolean;
  internationalisation: boolean;
  columns: DrawerColumnDraft[];
  preservedFields: any[];
};

function providerLabel(type: string) {
  if (type === "postgres") return "PostgreSQL";
  if (type === "mysql") return "MySQL";
  if (type === "mssql") return "MS SQL Server";
  return type;
}

const scalarFieldTypeOptions = [
  { value: "shortText", label: "Short Text" },
  { value: "longText", label: "Long Text" },
  { value: "richText", label: "Rich Text" },
  { value: "boolean", label: "Boolean" },
  { value: "int", label: "Integer" },
  { value: "bigint", label: "Big Integer" },
  { value: "decimal", label: "Decimal" },
  { value: "date", label: "Date" },
  { value: "datetime", label: "Date Time" },
  { value: "time", label: "Time" },
  { value: "json", label: "JSON" },
  { value: "uuid", label: "UUID" },
  { value: "email", label: "Email" },
  { value: "password", label: "Password" },
];

const scalarFieldTypeValueSet = new Set(scalarFieldTypeOptions.map((option) => option.value));
const mappingStrategyOptions = [
  { value: "generated_id", label: "Legacy generated id" },
  { value: "existing_id", label: "Legacy existing id" },
];

function getBaseClassNameForLegacyType(value: "none" | "existing_id" | "generated_id") {
  return value === "existing_id"
    ? "LegacyCommonEntityWithExistingId"
    : "LegacyCommonEntityWithGeneratedId";
}

function getSuperclassFieldNameForLegacyType(columnName: string, legacyTableType: "none" | "existing_id" | "generated_id") {
  const normalized = columnName.toLowerCase();
  const legacyFieldMap: Record<string, string> = {
    ss_created_at: "createdAt",
    ss_updated_at: "updatedAt",
    ss_deleted_at: "deletedAt",
    ss_deleted_tracker: "deletedTracker",
    ss_published_at: "publishedAt",
    ss_locale_name: "localeName",
    ss_default_entity_locale_id: "defaultEntityLocaleId",
    ss_created_by_id: "createdBy",
    ss_updated_by_id: "updatedBy",
  };

  if (normalized === "ss_id" && legacyTableType === "generated_id") {
    return "id";
  }

  return legacyFieldMap[normalized] ?? null;
}

function getSuggestedFieldNameForLegacyType(column: Pick<DrawerColumnDraft, "columnName" | "isAutoGenerated">, legacyTableType: "none" | "existing_id" | "generated_id") {
  if (legacyTableType === "existing_id" && column.isAutoGenerated) {
    return "id";
  }

  if (legacyTableType === "generated_id" && column.columnName.toLowerCase() === "id") {
    return "legacyId";
  }

  return camelCase(column.columnName.replace(/^ss_/i, ""));
}

function getDefaultOrmTypeForSolidFieldType(dataSourceType: string, solidFieldType: string) {
  const normalizedDatasourceType = dataSourceType.toLowerCase();

  const ormTypesByDatasource: Record<string, Record<string, string>> = {
    mssql: {
      shortText: "varchar",
      longText: "nvarchar",
      richText: "nvarchar",
      boolean: "bit",
      int: "int",
      bigint: "bigint",
      decimal: "numeric",
      date: "date",
      datetime: "datetime",
      time: "time",
      json: "simple-json",
      uuid: "uniqueidentifier",
      email: "nvarchar",
      password: "nvarchar",
    },
    mysql: {
      shortText: "varchar",
      longText: "longtext",
      richText: "longtext",
      boolean: "boolean",
      int: "int",
      bigint: "int",
      decimal: "decimal",
      date: "date",
      datetime: "datetime",
      time: "time",
      json: "json",
      uuid: "varchar",
      email: "varchar",
      password: "varchar",
    },
    postgres: {
      shortText: "varchar",
      longText: "text",
      richText: "text",
      boolean: "boolean",
      int: "integer",
      bigint: "bigint",
      decimal: "decimal",
      date: "date",
      datetime: "timestamp",
      time: "time",
      json: "json",
      uuid: "varchar",
      email: "varchar",
      password: "varchar",
    },
  };

  return ormTypesByDatasource[normalizedDatasourceType]?.[solidFieldType] ?? "varchar";
}

function statusLabel(record: DatasourceIntrospectionTableRecord) {
  return record.mapped ? "Mapped" : "Ready to map";
}

function readQueryError(error: any) {
  return (
    error?.data?.message
    || error?.error
    || error?.message
    || "Something went wrong."
  );
}

function isRecoverableGenerateCodeError(error: any) {
  const status = error?.status ?? error?.originalStatus;
  const message = [
    error?.error,
    error?.message,
    error?.data?.message,
    error?.data?.error,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();

  if (status === "FETCH_ERROR" || status === "TIMEOUT_ERROR" || status === "PARSING_ERROR") {
    return true;
  }

  return (
    message.includes("failed to fetch")
    || message.includes("network")
    || message.includes("load failed")
    || message.includes("fetch")
  );
}

function normalizeName(value: string) {
  return value.trim().toLowerCase();
}

function findMatchingModelField(column: DatasourceIntrospectionTableDetail["columns"][number], modelFields: any[]) {
  return modelFields.find((field) => {
    if (field?.isSystem) return false;

    const sameColumnName = normalizeName(field?.columnName ?? "") === normalizeName(column.columnName);
    if (sameColumnName) return true;

    return Boolean(column.isAutoGenerated && column.fieldName === "id" && field?.name === "id");
  }) ?? null;
}

function sanitizeExistingFieldPayload(field: any) {
  const {
    createdAt,
    updatedAt,
    deletedAt,
    model,
    mediaStorageProvider,
    identifier,
    ...rest
  } = field ?? {};

  if (mediaStorageProvider?.id && !rest.mediaStorageProviderId) {
    rest.mediaStorageProviderId = mediaStorageProvider.id;
  }

  return rest;
}

function buildDrawerDraft(
  tableDetail: DatasourceIntrospectionTableDetail,
  selectedTable: DatasourceIntrospectionTableRecord,
  mappedModelData?: any,
): DrawerDraft {
  const modelData = selectedTable.mapped ? (mappedModelData?.data ?? null) : null;
  const modelFields = modelData?.fields ?? [];
  const preservedFields = modelFields.map((field: any) => sanitizeExistingFieldPayload(field));
  const modelUserKeyField =
    modelData?.userKeyField?.name
    || modelFields.find((field: any) => field?.isUserKey)?.name
    || "";

  const columns: DrawerColumnDraft[] = tableDetail.columns.map((column) => {
    const matchingField = findMatchingModelField(column, modelFields);
    return {
      columnName: column.columnName,
      fieldName: matchingField?.name ?? column.fieldName,
      displayName: matchingField?.displayName ?? column.displayName,
      dataType: column.dataType,
      solidFieldType: matchingField?.type ?? column.solidFieldType,
      ormType: matchingField?.ormType ?? column.ormType,
      nullable: column.nullable,
      defaultValue: matchingField?.defaultValue ?? column.defaultValue,
      characterMaximumLength: column.characterMaximumLength,
      numericPrecision: column.numericPrecision,
      numericScale: column.numericScale,
      ordinalPosition: column.ordinalPosition,
      isAutoGenerated: column.isAutoGenerated,
      isDetectedPrimaryKey: column.isPrimaryKey,
      handledBySuperclass: column.handledBySuperclass,
      superclassFieldName: column.superclassFieldName,
      fieldId: matchingField?.id ?? null,
      include: column.handledBySuperclass ? false : Boolean(matchingField) || !selectedTable.mapped,
      matched: Boolean(matchingField),
      isPrimaryKey: Boolean(matchingField?.isPrimaryKey) || column.isPrimaryKey || (column.isAutoGenerated && column.fieldName === "id"),
    };
  });

  const draftUserKeyField = modelUserKeyField || tableDetail.suggestedMetadata.userKeyField;

  return {
    mapped: selectedTable.mapped,
    modelId: selectedTable.mappedModelId,
    mappedModuleLabel: selectedTable.mappedModuleDisplayName || selectedTable.mappedModuleName || null,
    singularName: modelData?.singularName ?? tableDetail.suggestedMetadata.singularName,
    pluralName: modelData?.pluralName ?? tableDetail.suggestedMetadata.pluralName,
    displayName: modelData?.displayName ?? tableDetail.suggestedMetadata.displayName,
    description: modelData?.description ?? tableDetail.suggestedMetadata.displayName,
    tableName: modelData?.tableName ?? tableDetail.suggestedMetadata.tableName,
    schema: tableDetail.suggestedMetadata.schema,
    dataSource: modelData?.dataSource ?? tableDetail.suggestedMetadata.dataSource,
    dataSourceType: modelData?.dataSourceType ?? tableDetail.suggestedMetadata.dataSourceType,
    legacyTableType: modelData?.legacyTableType ?? tableDetail.suggestedMetadata.legacyTableType,
    baseClassName: tableDetail.suggestedMetadata.baseClassName,
    userKeyField: draftUserKeyField,
    enableAuditTracking: modelData?.enableAuditTracking ?? true,
    enableSoftDelete: modelData?.enableSoftDelete ?? false,
    draftPublishWorkflow: modelData?.draftPublishWorkflow ?? false,
    internationalisation: modelData?.internationalisation ?? false,
    columns,
    preservedFields,
  };
}

function getDrawerValidationErrors(draft: DrawerDraft) {
  const errors: string[] = [];
  const includedColumns = draft.columns.filter((column) => !column.handledBySuperclass && column.include);
  const seenFieldNames = new Set<string>();

  if (!draft.singularName.trim()) {
    errors.push("Singular name is required.");
  }
  if (!draft.pluralName.trim()) {
    errors.push("Plural name is required.");
  }
  if (!draft.displayName.trim()) {
    errors.push("Display name is required.");
  }
  if (!includedColumns.length) {
    errors.push("Select at least one physical column to include in the mapping.");
  }

  for (const column of includedColumns) {
    const normalizedFieldName = column.fieldName.trim();
    if (!normalizedFieldName) {
      errors.push(`Field name is required for column "${column.columnName}".`);
      continue;
    }

    if (!column.displayName.trim()) {
      errors.push(`Field label is required for column "${column.columnName}".`);
      continue;
    }

    if (!scalarFieldTypeValueSet.has(column.solidFieldType)) {
      errors.push(`SolidX type "${column.solidFieldType}" is not allowed in step 1 for column "${column.columnName}".`);
      continue;
    }

    if (seenFieldNames.has(normalizedFieldName.toLowerCase())) {
      errors.push(`Field name "${normalizedFieldName}" is duplicated in the mapping draft.`);
      continue;
    }

    seenFieldNames.add(normalizedFieldName.toLowerCase());
  }

  if (!draft.userKeyField.trim()) {
    errors.push("Choose a user key field before saving the mapping.");
  } else {
    const userKeyExists = includedColumns.some((column) => column.fieldName === draft.userKeyField);
    if (!userKeyExists) {
      errors.push("The chosen user key field must remain part of the mapped columns.");
    }
  }

  if (draft.legacyTableType === "existing_id") {
    const hasPrimaryKey = includedColumns.some((column) => column.isPrimaryKey);
    if (!hasPrimaryKey) {
      errors.push("Legacy existing-id mappings must keep the generated id column mapped to field name \"id\".");
    }
  }

  return errors;
}

function buildMappingRequest(
  draft: DrawerDraft,
  plannedMigrationTimestamp?: number | null,
): DatasourceIntrospectionMappingRequest {
  return {
    mapped: draft.mapped,
    modelId: draft.modelId,
    singularName: draft.singularName.trim(),
    pluralName: draft.pluralName.trim(),
    displayName: draft.displayName.trim(),
    description: draft.description.trim() || draft.displayName.trim(),
    tableName: draft.tableName,
    schema: draft.schema ?? null,
    dataSource: draft.dataSource,
    dataSourceType: draft.dataSourceType,
    legacyTableType: draft.legacyTableType,
    baseClassName: draft.baseClassName,
    userKeyField: draft.userKeyField,
    enableAuditTracking: draft.enableAuditTracking,
    enableSoftDelete: draft.enableSoftDelete,
    draftPublishWorkflow: draft.draftPublishWorkflow,
    internationalisation: draft.internationalisation,
    plannedMigrationTimestamp: plannedMigrationTimestamp ?? null,
    columns: draft.columns.map((column) => ({
      columnName: column.columnName,
      fieldName: column.fieldName,
      displayName: column.displayName,
      dataType: column.dataType,
      solidFieldType: column.solidFieldType,
      ormType: column.ormType,
      nullable: column.nullable,
      defaultValue: column.defaultValue,
      characterMaximumLength: column.characterMaximumLength,
      numericPrecision: column.numericPrecision,
      numericScale: column.numericScale,
      ordinalPosition: column.ordinalPosition,
      isAutoGenerated: column.isAutoGenerated,
      handledBySuperclass: column.handledBySuperclass,
      superclassFieldName: column.superclassFieldName,
      fieldId: column.fieldId,
      include: column.include,
      matched: column.matched,
      isPrimaryKey: column.isPrimaryKey,
    })),
  };
}

function parseAndValidateReviewedModelJson(
  metadataJsonText: string,
  draft: DrawerDraft,
) {
  let parsed: any;

  try {
    parsed = JSON.parse(metadataJsonText);
  } catch (error: any) {
    return {
      error: `Metadata JSON is not valid JSON: ${error?.message ?? "Unknown parse error."}`,
      parsed: null,
    };
  }

  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    return {
      error: "Metadata JSON must be an object.",
      parsed: null,
    };
  }

  const requiredStringKeys = [
    "singularName",
    "pluralName",
    "displayName",
    "description",
    "dataSource",
    "dataSourceType",
    "tableName",
    "userKeyFieldUserKey",
  ];

  for (const key of requiredStringKeys) {
    if (typeof parsed[key] !== "string" || !parsed[key].trim()) {
      return {
        error: `Metadata JSON must include a non-empty "${key}" string.`,
        parsed: null,
      };
    }
  }

  const immutableChecks: Array<{ key: string; expected: string }> = [
    { key: "dataSource", expected: draft.dataSource },
    { key: "dataSourceType", expected: draft.dataSourceType },
    { key: "tableName", expected: draft.tableName },
    { key: "legacyTableType", expected: draft.legacyTableType },
  ];

  for (const check of immutableChecks) {
    if (`${parsed[check.key] ?? ""}` !== `${check.expected}`) {
      return {
        error: `Metadata JSON cannot change immutable binding key "${check.key}".`,
        parsed: null,
      };
    }
  }

  const requiredBooleanKeys = [
    "enableAuditTracking",
    "enableSoftDelete",
    "draftPublishWorkflow",
    "internationalisation",
  ];

  for (const key of requiredBooleanKeys) {
    if (typeof parsed[key] !== "boolean") {
      return {
        error: `Metadata JSON must include a boolean "${key}" value.`,
        parsed: null,
      };
    }
  }

  if (!Array.isArray(parsed.fields)) {
    return {
      error: "Metadata JSON must include a fields array.",
      parsed: null,
    };
  }

  const seenFieldNames = new Set<string>();
  for (const [index, field] of parsed.fields.entries()) {
    if (!field || typeof field !== "object" || Array.isArray(field)) {
      return {
        error: `Field at index ${index} is not a valid object.`,
        parsed: null,
      };
    }

    if (typeof field.name !== "string" || !field.name.trim()) {
      return {
        error: `Field at index ${index} must include a non-empty "name".`,
        parsed: null,
      };
    }

    if (typeof field.type !== "string" || !field.type.trim()) {
      return {
        error: `Field "${field.name}" must include a non-empty "type".`,
        parsed: null,
      };
    }

    if (typeof field.ormType !== "string" || !field.ormType.trim()) {
      return {
        error: `Field "${field.name}" must include a non-empty "ormType".`,
        parsed: null,
      };
    }

    if (typeof field.columnName !== "string" || !field.columnName.trim()) {
      return {
        error: `Field "${field.name}" must include a non-empty "columnName".`,
        parsed: null,
      };
    }

    const normalizedFieldName = field.name.trim().toLowerCase();
    if (seenFieldNames.has(normalizedFieldName)) {
      return {
        error: `Field name "${field.name}" is duplicated in metadata JSON.`,
        parsed: null,
      };
    }

    seenFieldNames.add(normalizedFieldName);
  }

  if (!parsed.fields.some((field: any) => field?.name === parsed.userKeyFieldUserKey && !field?.isMarkedForRemoval)) {
    return {
      error: "Metadata JSON must keep userKeyFieldUserKey present in the fields array.",
      parsed: null,
    };
  }

  return {
    error: null,
    parsed,
  };
}

export function DatasourceIntrospectionPage() {
  const params = useParams();
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const moduleId = Number(params.moduleId ?? 0);
  const isValidModuleId = Number.isFinite(moduleId) && moduleId > 0;

  const {
    data: bootstrap,
    isLoading: isBootstrapLoading,
    isFetching: isBootstrapFetching,
    error: bootstrapError,
    refetch: refetchBootstrap,
  } = useGetDatasourceIntrospectionBootstrapQuery(moduleId, {
    skip: !isValidModuleId,
  });

  const [selectedDatasource, setSelectedDatasource] = useState("");
  const [selectedRows, setSelectedRows] = useState<DatasourceIntrospectionTableRecord[]>([]);
  const [workspaceTableKey, setWorkspaceTableKey] = useState("");
  const [tableSearch, setTableSearch] = useState("");
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [settingsTab, setSettingsTab] = useState("datasource-info");
  const [drawerDraft, setDrawerDraft] = useState<DrawerDraft | null>(null);
  const [drawerTab, setDrawerTab] = useState("general-info");
  const [workspaceStep, setWorkspaceStep] = useState<WorkspaceStep>("configure");
  const [mappingPreview, setMappingPreview] = useState<DatasourceIntrospectionMappingPreview | null>(null);
  const [persistedMappingResult, setPersistedMappingResult] = useState<DatasourceIntrospectionApplyResponse | null>(null);
  const [migrationArtifactsResult, setMigrationArtifactsResult] = useState<DatasourceIntrospectionCreateMigrationResponse | null>(null);
  const [generateCodeOutput, setGenerateCodeOutput] = useState("");
  const [isGeneratingCodeWorkflow, setIsGeneratingCodeWorkflow] = useState(false);
  const [generateCodeStatusMessage, setGenerateCodeStatusMessage] = useState("");
  const [generateCodeTimeoutMessage, setGenerateCodeTimeoutMessage] = useState<string | null>(null);
  const [generateCodeReady, setGenerateCodeReady] = useState(false);
  const [hasAttemptedGenerateCode, setHasAttemptedGenerateCode] = useState(false);
  const [runMigrationOutput, setRunMigrationOutput] = useState("");
  const [runMigrationCompleted, setRunMigrationCompleted] = useState(false);
  const [reviewedMetadataJsonValue, setReviewedMetadataJsonValue] = useState<any>(null);
  const [metadataJsonText, setMetadataJsonText] = useState("");
  const [metadataJsonValidationError, setMetadataJsonValidationError] = useState<string | null>(null);
  const [metadataJsonResetToken, setMetadataJsonResetToken] = useState("initial");
  const [drawerBootstrapping, setDrawerBootstrapping] = useState(false);
  const [sessionSettings, setSessionSettings] = useState<SessionSettings>({
    relationInferenceEnabled: false,
    prioritizeUnmappedTables: true,
  });
  const [draftSessionSettings, setDraftSessionSettings] = useState<SessionSettings>(sessionSettings);
  const drawerBootstrapTimerRef = useRef<number | null>(null);

  const [
    previewMapping,
    { isLoading: isPreviewMappingLoading },
  ] = usePreviewDatasourceIntrospectionMappingMutation();

  const [
    applyMapping,
    { isLoading: isApplyMappingLoading },
  ] = useApplyDatasourceIntrospectionMappingMutation();
  const [
    createMigrationArtifacts,
    { isLoading: isCreateMigrationArtifactsLoading },
  ] = useCreateDatasourceIntrospectionMigrationArtifactsMutation();
  const [
    generateCode,
    { isLoading: isGenerateCodeLoading },
  ] = useGenerateDatasourceIntrospectionCodeMutation();
  const [
    runMigration,
    { isLoading: isRunMigrationLoading },
  ] = useRunDatasourceIntrospectionMigrationMutation();

  const isSavingMapping = isApplyMappingLoading;
  const isCreatingMigrationArtifacts = isCreateMigrationArtifactsLoading;

  useEffect(() => {
    if (!bootstrap) return;
    if (selectedDatasource) return;
    if (bootstrap.recommendedDatasourceName) {
      setSelectedDatasource(bootstrap.recommendedDatasourceName);
    }
  }, [bootstrap, selectedDatasource]);

  useEffect(() => {
    setSelectedRows([]);
    setWorkspaceTableKey("");
    setDrawerDraft(null);
    setTableSearch("");
    setWorkspaceStep("configure");
    setMappingPreview(null);
    setPersistedMappingResult(null);
    setMigrationArtifactsResult(null);
    setGenerateCodeOutput("");
    setIsGeneratingCodeWorkflow(false);
    setGenerateCodeStatusMessage("");
    setGenerateCodeTimeoutMessage(null);
    setGenerateCodeReady(false);
    setHasAttemptedGenerateCode(false);
    setRunMigrationOutput("");
    setRunMigrationCompleted(false);
    setReviewedMetadataJsonValue(null);
    setMetadataJsonText("");
    setMetadataJsonValidationError(null);
    setMetadataJsonResetToken(`datasource-${Date.now()}`);
  }, [selectedDatasource]);

  useEffect(() => () => {
    if (drawerBootstrapTimerRef.current) {
      window.clearTimeout(drawerBootstrapTimerRef.current);
    }
  }, []);

  const datasourceOptions = useMemo(
    () => (bootstrap?.datasources ?? []).map((datasource) => ({
      label: `${datasource.displayName} (${providerLabel(datasource.type)})`,
      value: datasource.name,
    })),
    [bootstrap],
  );

  const {
    data: tablesResponse,
    isLoading: isTablesLoading,
    isFetching: isTablesFetching,
    error: tablesError,
    refetch: refetchTables,
  } = useGetDatasourceIntrospectionTablesQuery(
    { moduleId, datasource: selectedDatasource },
    {
      skip: !isValidModuleId || !selectedDatasource,
    },
  );

  const selectedListRow = selectedRows[0] ?? null;
  const selectedListRowKey = selectedListRow ? `${selectedListRow.schema ?? ""}::${selectedListRow.tableName}` : "";
  const isWorkspaceMode = Boolean(workspaceTableKey);

  const selectedTable = useMemo(
    () => tablesResponse?.records?.find((record) => `${record.schema ?? ""}::${record.tableName}` === workspaceTableKey) ?? null,
    [tablesResponse, workspaceTableKey],
  );

  const {
    data: tableDetail,
    isLoading: isTableDetailLoading,
    isFetching: isTableDetailFetching,
    error: tableDetailError,
    refetch: refetchTableDetail,
  } = useGetDatasourceIntrospectionTableDetailQuery(
    {
      moduleId,
      datasource: selectedDatasource,
      table: selectedTable?.tableName ?? "",
      schema: selectedTable?.schema ?? undefined,
    },
    {
      skip: !isWorkspaceMode || !isValidModuleId || !selectedDatasource || !selectedTable || !!tablesResponse?.synchronizeBlocked,
    },
  );

  const {
    data: mappedModelResponse,
    isLoading: isMappedModelLoading,
    isFetching: isMappedModelFetching,
    error: mappedModelError,
  } = useGetmodelByIdQuery(selectedTable?.mappedModelId ?? 0, {
    skip: !isWorkspaceMode || !selectedTable?.mapped || !selectedTable?.mappedModelId,
  });

  const mappedModelData = mappedModelResponse?.data;
  const selectedDatasourceRecord = bootstrap?.datasources?.find((datasource) => datasource.name === selectedDatasource) ?? null;
  const drawerLoadingError = selectedTable?.mapped ? (tableDetailError || mappedModelError) : tableDetailError;
  const isDrawerBlockingLoading = Boolean(
    selectedTable
    && (
      drawerBootstrapping
      || !drawerDraft
      || isTableDetailLoading
      || isTableDetailFetching
      || (selectedTable.mapped && (isMappedModelLoading || isMappedModelFetching))
    ),
  );

  useEffect(() => {
    if (!isWorkspaceMode) {
      setDrawerDraft(null);
      return;
    }

    if (drawerBootstrapTimerRef.current) {
      window.clearTimeout(drawerBootstrapTimerRef.current);
    }

    setDrawerDraft(null);
    setDrawerTab("general-info");
    setWorkspaceStep("configure");
    setMappingPreview(null);
    setPersistedMappingResult(null);
    setMigrationArtifactsResult(null);
    setGenerateCodeOutput("");
    setIsGeneratingCodeWorkflow(false);
    setGenerateCodeStatusMessage("");
    setGenerateCodeTimeoutMessage(null);
    setGenerateCodeReady(false);
    setHasAttemptedGenerateCode(false);
    setRunMigrationOutput("");
    setRunMigrationCompleted(false);
    setReviewedMetadataJsonValue(null);
    setMetadataJsonText("");
    setMetadataJsonValidationError(null);
    setMetadataJsonResetToken(`table-${workspaceTableKey}-${Date.now()}`);
    setDrawerBootstrapping(true);
  }, [isWorkspaceMode, workspaceTableKey]);

  useEffect(() => {
    if (!isWorkspaceMode || !selectedTable) return;
    setSelectedRows([selectedTable]);
  }, [isWorkspaceMode, selectedTable]);

  useEffect(() => {
    if (!isWorkspaceMode || !selectedTable || !tableDetail) return;
    if (selectedTable.mapped && (!mappedModelData || mappedModelData.id !== selectedTable.mappedModelId)) return;

    if (drawerBootstrapTimerRef.current) {
      window.clearTimeout(drawerBootstrapTimerRef.current);
    }

    setDrawerDraft(buildDrawerDraft(
      tableDetail,
      selectedTable,
      selectedTable.mapped ? mappedModelResponse : undefined,
    ));
    drawerBootstrapTimerRef.current = window.setTimeout(() => {
      setDrawerBootstrapping(false);
    }, 150);
  }, [isWorkspaceMode, selectedTable, tableDetail, mappedModelData, mappedModelResponse]);

  const filteredRecords = useMemo(() => {
    const records = [...(tablesResponse?.records ?? [])];
    const searchNeedle = tableSearch.trim().toLowerCase();

    const filtered = searchNeedle
      ? records.filter((record) => {
        const haystack = `${record.tableName} ${record.schema ?? ""} ${record.mappedModelSingularName ?? ""} ${record.mappedModelDisplayName ?? ""} ${record.mappedModuleName ?? ""} ${record.mappedModuleDisplayName ?? ""}`.toLowerCase();
        return haystack.includes(searchNeedle);
      })
      : records;

    if (sessionSettings.prioritizeUnmappedTables) {
      filtered.sort((left, right) => {
        if (left.mapped !== right.mapped) {
          return left.mapped ? 1 : -1;
        }

        const leftLabel = `${left.schema ?? ""}.${left.tableName}`.toLowerCase();
        const rightLabel = `${right.schema ?? ""}.${right.tableName}`.toLowerCase();
        return leftLabel.localeCompare(rightLabel);
      });
    }

    return filtered;
  }, [sessionSettings.prioritizeUnmappedTables, tableSearch, tablesResponse?.records]);

  const drawerUserKeyOptions = useMemo(() => {
    const options = new Map<string, { label: string; value: string }>();

    tableDetail?.userKeyCandidates?.forEach((candidate) => {
      options.set(candidate.name, {
        label: `${candidate.label} · ${candidate.reason}`,
        value: candidate.name,
      });
    });

    drawerDraft?.columns
      .filter((column) => !column.handledBySuperclass && column.include)
      .forEach((column) => {
        if (!options.has(column.fieldName)) {
          options.set(column.fieldName, {
            label: `${column.fieldName} · mapped from ${column.columnName}`,
            value: column.fieldName,
          });
        }
      });

    return Array.from(options.values());
  }, [drawerDraft?.columns, tableDetail?.userKeyCandidates]);

  const settingsTabs = [
    {
      value: "datasource-info",
      label: "Datasource Info",
      content: (
        <div className="sdix-settings-grid">
          <div className="sdix-settings-static">
            <span>Target module</span>
            <strong>{bootstrap?.module?.displayName}</strong>
          </div>
          <div className="sdix-settings-static">
            <span>Default datasource</span>
            <strong>{bootstrap?.module?.defaultDataSource || "Not set"}</strong>
          </div>
          <div className="sdix-settings-static">
            <span>Datasource name</span>
            <strong>{selectedDatasourceRecord?.displayName || "Not selected"}</strong>
          </div>
          <div className="sdix-settings-static">
            <span>Datasource type</span>
            <strong>{selectedDatasourceRecord ? providerLabel(selectedDatasourceRecord.type) : "-"}</strong>
          </div>
          <div className="sdix-settings-static">
            <span>Host</span>
            <strong>{selectedDatasourceRecord?.host || "-"}</strong>
          </div>
          <div className="sdix-settings-static">
            <span>Port</span>
            <strong>{selectedDatasourceRecord?.port ?? "-"}</strong>
          </div>
          <div className="sdix-settings-static">
            <span>Database</span>
            <strong>{selectedDatasourceRecord?.database || "-"}</strong>
          </div>
          <div className="sdix-settings-static">
            <span>Env Prefix</span>
            <strong>{selectedDatasourceRecord?.envPrefix || "-"}</strong>
          </div>
          <div className="sdix-settings-static">
            <span>Synchronize</span>
            <strong>{selectedDatasourceRecord ? (selectedDatasourceRecord.synchronize === true ? "true" : "false") : "-"}</strong>
          </div>
        </div>
      ),
    },
    {
      value: "session-settings",
      label: "Session Settings",
      content: (
        <div className="sdix-settings-grid">
          <div className="sdix-settings-row">
            <div>
              <label>Relation inference</label>
              <p>Keep this off until we deliberately introduce relation discovery across engines.</p>
            </div>
            <SolidSwitch
              checked={draftSessionSettings.relationInferenceEnabled}
              onChange={(checked) => setDraftSessionSettings((current) => ({ ...current, relationInferenceEnabled: checked }))}
            />
          </div>

          <div className="sdix-settings-row">
            <div>
              <label>Prioritize unmapped tables</label>
              <p>Bubble unmapped tables to the top of the inventory so the first pass stays focused.</p>
            </div>
            <SolidSwitch
              checked={draftSessionSettings.prioritizeUnmappedTables}
              onChange={(checked) => setDraftSessionSettings((current) => ({ ...current, prioritizeUnmappedTables: checked }))}
            />
          </div>
        </div>
      ),
    },
  ];

  const handleRefresh = async () => {
    await refetchBootstrap();
    if (selectedDatasource) {
      await refetchTables();
    }
    if (isWorkspaceMode && selectedTable) {
      await refetchTableDetail();
    }
  };

  const startMappingForRecord = (record: DatasourceIntrospectionTableRecord) => {
    if (drawerBootstrapTimerRef.current) {
      window.clearTimeout(drawerBootstrapTimerRef.current);
    }

    setSelectedRows([record]);
    setWorkspaceTableKey(`${record.schema ?? ""}::${record.tableName}`);
  };

  const leaveWorkspace = () => {
    if (drawerBootstrapTimerRef.current) {
      window.clearTimeout(drawerBootstrapTimerRef.current);
    }

    setWorkspaceTableKey("");
    setDrawerDraft(null);
    setWorkspaceStep("configure");
    setDrawerTab("general-info");
    setMappingPreview(null);
    setPersistedMappingResult(null);
    setMigrationArtifactsResult(null);
    setGenerateCodeOutput("");
    setIsGeneratingCodeWorkflow(false);
    setGenerateCodeStatusMessage("");
    setGenerateCodeTimeoutMessage(null);
    setGenerateCodeReady(false);
    setHasAttemptedGenerateCode(false);
    setRunMigrationOutput("");
    setRunMigrationCompleted(false);
    setReviewedMetadataJsonValue(null);
    setMetadataJsonText("");
    setMetadataJsonValidationError(null);
    setMetadataJsonResetToken(`workspace-closed-${Date.now()}`);
    setDrawerBootstrapping(false);
  };

  const applyDraftSettings = () => {
    setSessionSettings(draftSessionSettings);
    setSettingsOpen(false);
  };

  const updateDrawerDraft = (updater: (current: DrawerDraft) => DrawerDraft) => {
    setMappingPreview(null);
    setPersistedMappingResult(null);
    setMigrationArtifactsResult(null);
    setGenerateCodeOutput("");
    setIsGeneratingCodeWorkflow(false);
    setGenerateCodeStatusMessage("");
    setGenerateCodeTimeoutMessage(null);
    setGenerateCodeReady(false);
    setHasAttemptedGenerateCode(false);
    setRunMigrationOutput("");
    setDrawerDraft((current) => (current ? updater(current) : current));
  };

  const updateGeneralField = (field: keyof DrawerDraft, value: any) => {
    updateDrawerDraft((current) => ({ ...current, [field]: value }));
  };

  const updateColumnFieldName = (columnName: string, nextFieldName: string) => {
    updateDrawerDraft((current) => ({
      ...current,
      columns: current.columns.map((column) => {
        if (column.columnName !== columnName) return column;

        const previousSuggestedLabel = startCase(column.fieldName);
        const nextNormalizedFieldName = camelCase(nextFieldName);
        return {
          ...column,
          fieldName: nextNormalizedFieldName,
          displayName: !column.displayName.trim() || column.displayName === previousSuggestedLabel
            ? startCase(nextNormalizedFieldName)
            : column.displayName,
        };
      }),
      userKeyField: current.userKeyField === current.columns.find((column) => column.columnName === columnName)?.fieldName
        ? camelCase(nextFieldName)
        : current.userKeyField,
    }));
  };

  const updateColumnDisplayName = (columnName: string, nextDisplayName: string) => {
    updateDrawerDraft((current) => ({
      ...current,
      columns: current.columns.map((column) => (
        column.columnName === columnName
          ? { ...column, displayName: nextDisplayName }
          : column
      )),
    }));
  };

  const updateColumnSolidFieldType = (columnName: string, nextSolidFieldType: string) => {
    updateDrawerDraft((current) => ({
      ...current,
      columns: current.columns.map((column) => {
        if (column.columnName !== columnName) return column;
        if (column.handledBySuperclass) return column;

        return {
          ...column,
          solidFieldType: nextSolidFieldType,
          ormType: getDefaultOrmTypeForSolidFieldType(current.dataSourceType, nextSolidFieldType),
        };
      }),
    }));
  };

  const updateLegacyTableType = (legacyTableType: "none" | "existing_id" | "generated_id") => {
    updateDrawerDraft((current) => {
      const renamedUserKeyColumns = new Map<string, string>();

      const columns = current.columns.map((column) => {
        const nextSuperclassFieldName = getSuperclassFieldNameForLegacyType(column.columnName, legacyTableType);
        const nextHandledBySuperclass = Boolean(nextSuperclassFieldName);
        const nextSuggestedFieldName = getSuggestedFieldNameForLegacyType(column, legacyTableType);
        const shouldRebuildFieldName = column.handledBySuperclass !== nextHandledBySuperclass
          || (legacyTableType === "existing_id" && column.isAutoGenerated && (column.fieldName === "id" || column.fieldName === "legacyId"))
          || (legacyTableType === "generated_id" && column.columnName.toLowerCase() === "id");
        const nextFieldName = shouldRebuildFieldName ? nextSuggestedFieldName : column.fieldName;
        const nextDisplayName = !column.displayName.trim() || column.displayName === startCase(column.fieldName)
          ? startCase(nextFieldName)
          : column.displayName;
        const nextInclude = nextHandledBySuperclass
          ? false
          : (legacyTableType === "existing_id" && column.isAutoGenerated ? true : column.include);
        const nextIsPrimaryKey = (
          legacyTableType === "existing_id" && column.isAutoGenerated && nextFieldName === "id"
        ) || (
          legacyTableType === "generated_id" && column.isDetectedPrimaryKey
        );

        if (current.userKeyField === column.fieldName && current.userKeyField !== nextFieldName) {
          renamedUserKeyColumns.set(column.fieldName, nextFieldName);
        }

        return {
          ...column,
          fieldName: nextFieldName,
          displayName: nextDisplayName,
          handledBySuperclass: nextHandledBySuperclass,
          superclassFieldName: nextSuperclassFieldName,
          include: nextInclude,
          isPrimaryKey: nextIsPrimaryKey,
        };
      });

      return {
        ...current,
        legacyTableType,
        baseClassName: getBaseClassNameForLegacyType(legacyTableType),
        columns,
        userKeyField: renamedUserKeyColumns.get(current.userKeyField) ?? current.userKeyField,
      };
    });
  };

  const setColumnIncluded = (columnName: string, include: boolean) => {
    updateDrawerDraft((current) => ({
      ...current,
      columns: current.columns.map((column) => {
        if (column.columnName !== columnName) return column;
        if (column.handledBySuperclass || column.isPrimaryKey) return column;
        return { ...column, include };
      }),
    }));
  };

  const changeUserKeyField = (fieldName: string) => {
    updateDrawerDraft((current) => ({
      ...current,
      userKeyField: fieldName,
      columns: current.columns.map((column) => (
        column.fieldName === fieldName
          ? { ...column, include: column.handledBySuperclass ? false : true }
          : column
      )),
    }));
  };

  const setUnmappedColumnsIncluded = (include: boolean) => {
    updateDrawerDraft((current) => ({
      ...current,
      columns: current.columns.map((column) => {
        if (column.handledBySuperclass || column.matched || column.isPrimaryKey) {
          return column;
        }
        return { ...column, include };
      }),
    }));
  };

  const openMappedModelForm = () => {
    const targetModelId = drawerDraft?.modelId ?? selectedTable?.mappedModelId;
    if (!targetModelId) return;
    window.open(`/admin/core/solid-core/model-metadata/form/${targetModelId}`, "_blank", "noopener,noreferrer");
  };

  const reviewMappingJson = async () => {
    if (!drawerDraft || !bootstrap?.module?.id) return;

    const validationErrors = getDrawerValidationErrors(drawerDraft);
    if (validationErrors.length) {
      validationErrors.forEach((detail) => {
        dispatch(showToast({ severity: "error", summary: "Validation", detail }));
      });
      return;
    }

    try {
      const preview = await previewMapping({
        moduleId: bootstrap.module.id,
        payload: buildMappingRequest(drawerDraft),
      }).unwrap();

      setMappingPreview(preview);
      setReviewedMetadataJsonValue(preview.metadataJson.model);
      setMetadataJsonText(JSON.stringify(preview.metadataJson.model, null, 2));
      setMetadataJsonValidationError(null);
      setMetadataJsonResetToken(`preview-${preview.metadataJson.filePath}-${Date.now()}`);
      setPersistedMappingResult(null);
      setMigrationArtifactsResult(null);
      setGenerateCodeOutput("");
      setRunMigrationOutput("");
      setWorkspaceStep("review-json");
    } catch (error: any) {
      dispatch(showToast({
        severity: "error",
        summary: "Preview failed",
        detail: readQueryError(error),
      }));
    }
  };

  const persistMappingArtifacts = async () => {
    if (!drawerDraft || !bootstrap?.module?.id) return;

    const validationErrors = getDrawerValidationErrors(drawerDraft);
    if (validationErrors.length) {
      validationErrors.forEach((detail) => {
        dispatch(showToast({ severity: "error", summary: "Validation", detail }));
      });
      setWorkspaceStep("configure");
      return;
    }

    const reviewedModelValidation = parseAndValidateReviewedModelJson(metadataJsonText, drawerDraft);
    if (reviewedModelValidation.error || !reviewedModelValidation.parsed) {
      setMetadataJsonValidationError(reviewedModelValidation.error ?? "Metadata JSON is invalid.");
      setWorkspaceStep("review-json");
      dispatch(showToast({
        severity: "error",
        summary: "Validation",
        detail: reviewedModelValidation.error ?? "Metadata JSON is invalid.",
      }));
      return;
    }

    setMetadataJsonValidationError(null);

    try {
      const response = await applyMapping({
        moduleId: bootstrap.module.id,
        payload: {
          ...buildMappingRequest(drawerDraft, mappingPreview?.migration.timestamp ?? null),
          reviewedModel: reviewedModelValidation.parsed,
        },
      }).unwrap();

      dispatch(showToast({
        severity: "success",
        summary: "Mapping saved",
        detail: drawerDraft.mapped
          ? "The model mapping metadata was updated successfully."
          : "The model mapping metadata was created successfully.",
      }));

      setPersistedMappingResult(response);
      setMigrationArtifactsResult(null);
      setGenerateCodeOutput("");
      setIsGeneratingCodeWorkflow(false);
      setGenerateCodeStatusMessage("");
      setGenerateCodeTimeoutMessage(null);
      setGenerateCodeReady(false);
      setHasAttemptedGenerateCode(false);
      setRunMigrationOutput("");
      setRunMigrationCompleted(false);
      setDrawerDraft((current) => (
        current
          ? {
            ...current,
            mapped: true,
            modelId: response.modelId,
          }
          : current
      ));
      setWorkspaceStep("generate-code");
    } catch (error: any) {
      dispatch(showToast({
        severity: "error",
        summary: "Save failed",
        detail: readQueryError(error),
      }));
    }
  };

  const handleGenerateCode = async () => {
    if (!bootstrap?.module?.id) return;

    setHasAttemptedGenerateCode(true);
    setRunMigrationCompleted(false);
    setIsGeneratingCodeWorkflow(true);
    setGenerateCodeStatusMessage("Submitting module generate-code request...");
    setGenerateCodeTimeoutMessage(null);
    setGenerateCodeReady(false);
    let responseMessage = "";

    try {
      const response = await generateCode({ moduleId: bootstrap.module.id }).unwrap();
      responseMessage = response.output || response.message || "";
      setGenerateCodeOutput(responseMessage);
      setGenerateCodeStatusMessage("Waiting briefly for the backend restart window...");
    } catch (error: any) {
      if (!isRecoverableGenerateCodeError(error)) {
        setIsGeneratingCodeWorkflow(false);
        setGenerateCodeStatusMessage("");
        setGenerateCodeTimeoutMessage(null);
        setGenerateCodeReady(false);
        dispatch(showToast({
          severity: "error",
          summary: "Generate code failed",
          detail: readQueryError(error),
        }));
        return;
      }

      setGenerateCodeStatusMessage("The API connection dropped during restart. Waiting for the backend to come back online...");
    }

    await new Promise((resolve) => window.setTimeout(resolve, 5000));
    setGenerateCodeStatusMessage("Checking if the backend is back online...");

    const isBackendAvailable = await waitForBackendAvailability({
      retries: 40,
      delayMs: 1500,
    });

    setIsGeneratingCodeWorkflow(false);

    if (!isBackendAvailable) {
      setGenerateCodeTimeoutMessage(
        "Code generation took longer than expected. The backend did not come back within 60 seconds, so there may be a compilation failure or another startup issue. Please review the generated code manually and check the API logs before continuing.",
      );
      dispatch(showToast({
        severity: "warn",
        summary: "Backend restart taking too long",
        detail: "The generate-code request completed, but the backend did not come back within 60 seconds.",
      }));
      return;
    }

    setGenerateCodeStatusMessage("Backend is back online. You can continue.");
    setGenerateCodeReady(true);
    setMigrationArtifactsResult(null);
    setRunMigrationOutput("");
    dispatch(showToast({
      severity: "success",
      summary: "Code generated",
      detail: responseMessage || "The backend is back online. You can continue to the migration artifacts step.",
    }));
  };

  const handleCreateMigrationArtifacts = async () => {
    if (!drawerDraft || !bootstrap?.module?.id || !persistedMappingResult?.modelId) return;

    const reviewedModelValidation = parseAndValidateReviewedModelJson(metadataJsonText, drawerDraft);
    if (reviewedModelValidation.error || !reviewedModelValidation.parsed) {
      setMetadataJsonValidationError(reviewedModelValidation.error ?? "Metadata JSON is invalid.");
      setWorkspaceStep("review-json");
      dispatch(showToast({
        severity: "error",
        summary: "Validation",
        detail: reviewedModelValidation.error ?? "Metadata JSON is invalid.",
      }));
      return;
    }

    try {
      const response = await createMigrationArtifacts({
        moduleId: bootstrap.module.id,
        payload: {
          ...buildMappingRequest(
            {
              ...drawerDraft,
              mapped: true,
              modelId: persistedMappingResult.modelId,
            },
            mappingPreview?.migration.timestamp ?? null,
          ),
          reviewedModel: reviewedModelValidation.parsed,
        },
      }).unwrap();

      setMigrationArtifactsResult(response);
      setWorkspaceStep("run-migration");
      dispatch(showToast({
        severity: "success",
        summary: "Migration artifacts created",
        detail: response.migration.written
          ? "The migration file and datasource registration were written successfully."
          : "No migration file was required, but the datasource registration was updated successfully.",
      }));
    } catch (error: any) {
      dispatch(showToast({
        severity: "error",
        summary: "Create migration artifacts failed",
        detail: readQueryError(error),
      }));
    }
  };

  const handleRunMigration = async () => {
    if (!bootstrap?.module?.id || !selectedDatasource) return;

    try {
      const response = await runMigration({
        moduleId: bootstrap.module.id,
        datasource: selectedDatasource,
      }).unwrap();

      setRunMigrationOutput(response.output || response.message || "");
      setRunMigrationCompleted(true);
      dispatch(showToast({
        severity: "success",
        summary: "Migration workflow complete",
        detail: response.message || `Migration, build, and seed ran successfully for datasource "${selectedDatasource}".`,
      }));

      await refetchTables();
      await refetchBootstrap();
    } catch (error: any) {
      setRunMigrationOutput(readQueryError(error));
      dispatch(showToast({
        severity: "error",
        summary: "Run migration failed",
        detail: readQueryError(error),
      }));
    }
  };

  if (!isValidModuleId) {
    return (
      <div className="sdix-page">
        <div className="sdix-empty-state">
          <ShieldAlert size={24} />
          <h2>Module not found</h2>
          <p>Open datasource introspection from a saved module so SolidX knows which module should receive the mapped models.</p>
        </div>
      </div>
    );
  }

  const stepSequence: WorkspaceStep[] = [
    "configure",
    "review-json",
    "generate-code",
    "create-migrations",
    "run-migration",
  ];
  const currentStepIndex = stepSequence.indexOf(workspaceStep);
  const stepperItems = [
    {
      key: "configure" as const,
      label: "Configure Mapping",
      complete: currentStepIndex > 0,
      active: workspaceStep === "configure",
      disabled: false,
      onClick: () => setWorkspaceStep("configure"),
    },
    {
      key: "review-json" as const,
      label: "Review Mapping JSON",
      complete: currentStepIndex > 1,
      active: workspaceStep === "review-json",
      disabled: !mappingPreview,
      onClick: () => {
        if (mappingPreview) setWorkspaceStep("review-json");
      },
    },
    {
      key: "generate-code" as const,
      label: "Generate Code",
      complete: currentStepIndex > 2,
      active: workspaceStep === "generate-code",
      disabled: !persistedMappingResult,
      onClick: () => {
        if (persistedMappingResult) setWorkspaceStep("generate-code");
      },
    },
    {
      key: "create-migrations" as const,
      label: "Create Migrations",
      complete: currentStepIndex > 3,
      active: workspaceStep === "create-migrations",
      disabled: !hasAttemptedGenerateCode,
      onClick: () => {
        if (hasAttemptedGenerateCode) setWorkspaceStep("create-migrations");
      },
    },
    {
      key: "run-migration" as const,
      label: "Run Migration",
      complete: false,
      active: workspaceStep === "run-migration",
      disabled: !migrationArtifactsResult,
      onClick: () => {
        if (migrationArtifactsResult) setWorkspaceStep("run-migration");
      },
    },
  ];

  const selectableUnmappedColumns = drawerDraft?.columns.filter(
    (column) => !column.handledBySuperclass && !column.matched && !column.isPrimaryKey,
  ) ?? [];
  const allSelectableUnmappedIncluded = selectableUnmappedColumns.length > 0
    && selectableUnmappedColumns.every((column) => column.include);
  const drawerRawDdl = tableDetail?.rawDdl ?? null;
  const drawerTabs = drawerDraft ? [
    {
      value: "general-info",
      label: "General Info",
      content: (
        <div className="sdix-drawer-form">
          <section className="sdix-form-section">
            <h4 className="solid-form-layout-label">Model Info</h4>
            <div className="sdix-form-grid">
              <div className="sdix-form-field">
                <label htmlFor="sdix-singular-name">Singular Name</label>
                <SolidInput
                  id="sdix-singular-name"
                  value={drawerDraft.singularName}
                  onChange={(event) => updateGeneralField("singularName", event.target.value)}
                />
              </div>
              <div className="sdix-form-field">
                <label htmlFor="sdix-plural-name">Plural Name</label>
                <SolidInput
                  id="sdix-plural-name"
                  value={drawerDraft.pluralName}
                  onChange={(event) => updateGeneralField("pluralName", event.target.value)}
                />
              </div>
              <div className="sdix-form-field">
                <label htmlFor="sdix-display-name">Display Name</label>
                <SolidInput
                  id="sdix-display-name"
                  value={drawerDraft.displayName}
                  onChange={(event) => updateGeneralField("displayName", event.target.value)}
                />
              </div>
              <div className="sdix-form-field">
                <label htmlFor="sdix-user-key-field">User Key Field</label>
                    <SolidSelect
                      id="sdix-user-key-field"
                      value={drawerDraft.userKeyField}
                      options={drawerUserKeyOptions}
                      placeholder="Select user key field"
                  onChange={(event) => changeUserKeyField(event.value)}
                />
              </div>
              <div className="sdix-form-field sdix-form-field--full">
                <label htmlFor="sdix-description">Description</label>
                <SolidTextarea
                  className="sdix-description-textarea"
                  id="sdix-description"
                  rows={2}
                  value={drawerDraft.description}
                  onChange={(event) => updateGeneralField("description", event.target.value)}
                />
              </div>
            </div>
          </section>

          <section className="sdix-form-section">
            <h4 className="solid-form-layout-label">Datasource Binding</h4>
            <div className="sdix-form-grid">
              <div className="sdix-form-field">
                <label htmlFor="sdix-table-name">Table Name</label>
                <SolidInput
                  id="sdix-table-name"
                  value={drawerDraft.tableName}
                  onChange={(event) => updateGeneralField("tableName", event.target.value)}
                />
              </div>
              <div className="sdix-form-field">
                <label htmlFor="sdix-schema-name">Schema</label>
                <SolidInput
                  id="sdix-schema-name"
                  value={drawerDraft.schema ?? "default"}
                  disabled
                />
              </div>
              <div className="sdix-form-field">
                <label htmlFor="sdix-datasource-name">Datasource</label>
                <SolidInput
                  id="sdix-datasource-name"
                  value={drawerDraft.dataSource}
                  disabled
                />
              </div>
              <div className="sdix-form-field">
                <label htmlFor="sdix-datasource-type">Provider</label>
                <SolidInput
                  id="sdix-datasource-type"
                  value={providerLabel(drawerDraft.dataSourceType)}
                  disabled
                />
              </div>
              <div className="sdix-form-field">
                <label htmlFor="sdix-legacy-type">Mapping Strategy</label>
                <SolidSelect
                  id="sdix-legacy-type"
                  value={drawerDraft.legacyTableType}
                  options={mappingStrategyOptions}
                  onChange={(event) => updateLegacyTableType(event.value)}
                />
                <small className="sdix-inline-note">
                  This will use <strong>{drawerDraft.baseClassName}</strong> for the generated entity.
                </small>
              </div>
            </div>
          </section>
        </div>
      ),
    },
    {
      value: "columns-mapping",
      label: "Columns Mapping",
      content: (
        <div className="sdix-columns">
          <div className="sdix-columns__toolbar">
            <div className="sdix-columns__legend" aria-label="Column legend">
              <span className="sdix-status-badge is-superclass">System column</span>
              <span className="sdix-status-badge is-muted">Application column</span>
            </div>
          </div>
          <div className="sdix-column-table">
            <div className="sdix-column-row sdix-column-row--head sdix-column-row--mapping">
              <span className="sdix-column-select-header">
                {selectableUnmappedColumns.length ? (
                  <SolidCheckbox
                    checked={allSelectableUnmappedIncluded}
                    onChange={(event) => setUnmappedColumnsIncluded(event.target.checked)}
                    aria-label={allSelectableUnmappedIncluded ? "Deselect all unmapped columns" : "Select all unmapped columns"}
                  />
                ) : (
                  "Include"
                )}
              </span>
              <span>Column</span>
              <span>Field</span>
              <span>Label</span>
              <span>Database</span>
              <span>SolidX</span>
              <span>Status</span>
              <span>Action</span>
            </div>
            {drawerDraft.columns.map((column) => {
              const isUserKey = drawerDraft.userKeyField === column.fieldName;
              const isPrimaryKeyField = column.isPrimaryKey;
              const statusClassName = column.handledBySuperclass
                ? "is-superclass"
                : column.include
                  ? column.matched
                    ? "is-mapped"
                    : "is-unmapped"
                  : "is-muted";

              const statusText = column.handledBySuperclass
                ? "System"
                : column.include
                  ? column.matched
                    ? "Mapped"
                    : "Queued for save"
                  : column.matched
                    ? "Currently omitted"
                    : "Skipped for now";

              return (
                <div key={column.columnName} className="sdix-column-row sdix-column-row--mapping">
                  <span className="sdix-column-include">
                    {column.handledBySuperclass ? (
                      <span className="sdix-column-placeholder">-</span>
                    ) : column.matched ? (
                      <span className="sdix-column-placeholder">-</span>
                    ) : column.isPrimaryKey ? (
                      <SolidCheckbox checked disabled aria-label="Required included column" />
                    ) : (
                      <SolidCheckbox
                        checked={column.include}
                        onChange={(event) => setColumnIncluded(column.columnName, event.target.checked)}
                      />
                    )}
                  </span>
                  <span className="sdix-column-meta">
                    <strong>{column.columnName}</strong>
                    {column.isAutoGenerated ? <small>Generated id column</small> : null}
                  </span>
                  <span>
                    <SolidInput
                      value={column.fieldName}
                      disabled={column.handledBySuperclass}
                      onChange={(event) => updateColumnFieldName(column.columnName, event.target.value)}
                    />
                    {isUserKey || isPrimaryKeyField ? (
                      <div className="sdix-inline-note-stack">
                        {isUserKey ? <small className="sdix-inline-note">User key</small> : null}
                        {isPrimaryKeyField ? <small className="sdix-inline-note">Primary key</small> : null}
                      </div>
                    ) : null}
                  </span>
                  <span>
                    <SolidInput
                      value={column.displayName}
                      disabled={column.handledBySuperclass}
                      onChange={(event) => updateColumnDisplayName(column.columnName, event.target.value)}
                    />
                  </span>
                  <span className="sdix-column-meta">
                    <strong>{column.dataType}</strong>
                  </span>
                  <span>
                    {column.handledBySuperclass ? (
                      <span>{column.solidFieldType}</span>
                    ) : (
                      <SolidSelect
                        value={column.solidFieldType}
                        options={scalarFieldTypeOptions}
                        onChange={(event) => updateColumnSolidFieldType(column.columnName, event.value)}
                      />
                    )}
                  </span>
                  <span>
                    <span className={`sdix-status-badge ${statusClassName}`}>{statusText}</span>
                  </span>
                  <span className="sdix-column-action">
                    {column.handledBySuperclass ? (
                      <SolidButton size="small" variant="outline" disabled className="sdix-column-action-chip sdix-column-action-chip--managed">
                        Managed
                      </SolidButton>
                    ) : column.isPrimaryKey ? (
                      <SolidButton size="small" variant="outline" disabled className="sdix-column-action-chip sdix-column-action-chip--required">
                        Required
                      </SolidButton>
                    ) : column.matched ? (
                      <SolidButton size="small" variant="outline" onClick={() => setColumnIncluded(column.columnName, false)}>
                        Remove mapping
                      </SolidButton>
                    ) : (
                      <span className="sdix-column-placeholder">-</span>
                    )}
                  </span>
                </div>
              );
            })}
          </div>
        </div>
      ),
    },
    {
      value: "raw-ddl",
      label: "Raw DDL",
      content: (
        <div className="sdix-ddl-tab">
          {drawerRawDdl?.available && drawerRawDdl.statement ? (
            <pre className="sdix-ddl-code"><code>{drawerRawDdl.statement}</code></pre>
          ) : (
            <div className="sdix-empty-state is-inline sdix-ddl-empty">
              <Database size={18} />
              <p>{drawerRawDdl?.note || "DDL preview is not available for this table."}</p>
            </div>
          )}
        </div>
      ),
    },
  ] : [];

  const reviewJsonPanel = mappingPreview ? (
    <div className="sdix-review-panel sdix-review-panel--metadata">
      <div className="sdix-review-meta sdix-review-meta--compact">
        <span>Target file</span>
        <strong>{mappingPreview.metadataJson.filePath}</strong>
      </div>
      <SolidJsonEditor
        className="sdix-json-editor"
        value={reviewedMetadataJsonValue ?? mappingPreview.metadataJson.model}
        resetToken={metadataJsonResetToken}
        onValueChange={(nextValue) => {
          setReviewedMetadataJsonValue(nextValue);
          if (metadataJsonValidationError) {
            setMetadataJsonValidationError(null);
          }
        }}
        onTextChange={(nextText) => {
          setMetadataJsonText(nextText);
        }}
        onErrorChange={setMetadataJsonValidationError}
      />
      {metadataJsonValidationError ? (
        <div className="sdix-json-validation-error">
          <span>{metadataJsonValidationError}</span>
        </div>
      ) : null}
    </div>
  ) : null;

  const createMigrationsPanel = mappingPreview ? (
    <div className="sdix-review-panel sdix-review-panel--migration">
      {mappingPreview.migration.willGenerate && mappingPreview.migration.filePath ? (
        <>
          <div className="sdix-review-meta sdix-review-meta--compact">
            <span>Target file</span>
            <strong>{mappingPreview.migration.filePath}</strong>
          </div>
          <p className="sdix-review-note">
            This migration preview is generated from the current mapping and stays read-only here. Moving ahead writes the migration file to disk and updates the datasource registration now that the entity code already exists.
          </p>
          {mappingPreview.migration.content ? (
            <pre className="sdix-ddl-code sdix-ddl-code--fill"><code>{mappingPreview.migration.content}</code></pre>
          ) : null}
        </>
      ) : (
        <div className="sdix-empty-state is-inline sdix-ddl-empty">
          <Database size={18} />
          <p>{mappingPreview.migration.note}</p>
        </div>
      )}
    </div>
  ) : null;

  const generateCodePanel = (
    <div className="sdix-stage-panel">
      <div className="sdix-stage-panel__header">
        <span className="sdix-stage-panel__eyebrow">Step 3</span>
        <h3>Generate module code</h3>
        <p>The reviewed metadata JSON is now persisted. Run the normal SolidX module generation flow next so the entity, DTOs, repository, service, controller, and UI code are refreshed before we register the entity on the datasource and write the migration.</p>
      </div>
      <div className="sdix-stage-panel__body">
        <div className="sdix-stage-panel__card">
          <div className="sdix-stage-panel__card-title">What happens here</div>
          <ul className="sdix-stage-panel__list">
            <li>The module generate-code pipeline runs for <strong>{bootstrap?.module?.displayName}</strong>.</li>
            <li>The newly mapped model entity is generated inside the module source folder.</li>
            <li>Any existing generated assets for this module may be refreshed.</li>
          </ul>
        </div>
        <div className="sdix-stage-panel__actions">
          <SolidButton
            leftIcon={<Sparkles size={14} />}
            loading={isGenerateCodeLoading || isGeneratingCodeWorkflow}
            disabled={isGenerateCodeLoading || isGeneratingCodeWorkflow}
            onClick={() => void handleGenerateCode()}
          >
            Generate Code
          </SolidButton>
        </div>
        {isGeneratingCodeWorkflow ? (
          <div className="sdix-empty-state is-inline sdix-stage-progress">
            <SolidSpinner size={30} />
            <h3>Generating code</h3>
            <p>{generateCodeStatusMessage || "Waiting for the backend to finish restarting..."}</p>
          </div>
        ) : null}
        {!isGeneratingCodeWorkflow && generateCodeTimeoutMessage ? (
          <div className="sdix-error is-inline sdix-stage-progress sdix-stage-progress--warning">
            <ShieldAlert size={22} />
            <h3>Manual review recommended</h3>
            <p>{generateCodeTimeoutMessage}</p>
          </div>
        ) : null}
        {generateCodeOutput ? (
          <pre className="sdix-ddl-code sdix-ddl-code--fill"><code>{generateCodeOutput}</code></pre>
        ) : null}
      </div>
    </div>
  );

  const runMigrationPanel = (
    <div className="sdix-stage-panel">
      <div className="sdix-stage-panel__header">
        <span className="sdix-stage-panel__eyebrow">Step 5</span>
        <h3>Run migration, build, and seed</h3>
        <p>With the datasource file updated and module code generated, SolidX can now run the TypeORM migration for the selected datasource, rebuild the project, and reseed the mapped module metadata.</p>
      </div>
      <div className="sdix-stage-panel__body">
        <div className="sdix-stage-panel__card">
          <div className="sdix-stage-panel__card-title">Commands</div>
          <pre className="sdix-stage-panel__command"><code>{`npx @solidxai/solidctl@latest migration -d ${selectedDatasource} run
npx @solidxai/solidctl@latest build
npx @solidxai/solidctl@latest seed --modules-to-seed ${bootstrap?.module?.name || ""}`}</code></pre>
        </div>
        {runMigrationCompleted ? (
          <div className="sdix-empty-state is-inline sdix-stage-progress">
            <Check size={24} />
            <h3>Migration workflow finished</h3>
            <p>Review the command output below. When you are satisfied, click Finish to return to the model list.</p>
          </div>
        ) : null}
        {runMigrationOutput ? (
          <pre className="sdix-ddl-code sdix-ddl-code--fill"><code>{runMigrationOutput}</code></pre>
        ) : null}
      </div>
    </div>
  );

  const workspaceContent = drawerDraft ? (() => {
    switch (workspaceStep) {
      case "review-json":
        return reviewJsonPanel;
      case "create-migrations":
        return createMigrationsPanel;
      case "generate-code":
        return generateCodePanel;
      case "run-migration":
        return runMigrationPanel;
      case "configure":
      default:
        return (
          <SolidTabGroup
            tabs={drawerTabs}
            value={drawerTab}
            onValueChange={setDrawerTab}
            className="sdix-drawer-tabs sdix-wizard-tabs"
            panelClassName="sdix-drawer-tab-panel sdix-wizard-tab-panel"
          />
        );
    }
  })() : null;

  const workspaceMeta = drawerDraft ? (() => {
    switch (workspaceStep) {
      case "review-json":
        return (
          <span>
            Review the generated metadata JSON before it is written to the module metadata file.
          </span>
        );
      case "generate-code":
        return persistedMappingResult ? (
          <span>
            Metadata JSON has been saved for
            {" "}
            <strong>{drawerDraft.displayName || drawerDraft.singularName}</strong>
            . Generate the module code next so the entity file exists before datasource registration is updated. Continue stays disabled until you attempt code generation at least once.
          </span>
        ) : (
          <span>Save the metadata JSON before generating code.</span>
        );
      case "create-migrations":
        return mappingPreview ? (
          <span>
            Create the migration artifacts for
            {" "}
            <strong>{mappingPreview.summary.includedColumnNames.length}</strong>
            {" "}
            mapped columns
            {mappingPreview.summary.generatedSystemColumnCount
              ? ` and ${mappingPreview.summary.generatedSystemColumnCount} SolidX system column migration changes`
              : ""}
            .
          </span>
        ) : null;
      case "run-migration":
        return runMigrationCompleted ? (
          <span>
            The migration, build, and seed workflow has completed for
            {" "}
            <strong>{selectedDatasource}</strong>
            . Review the output below and click Finish when you are ready to return to the model list.
          </span>
        ) : (
          <span>
            Run the migration, build, and seed workflow for
            {" "}
            <strong>{selectedDatasource}</strong>
            {" "}
            to apply the SolidX system columns on the legacy table and refresh the module metadata state.
          </span>
        );
      case "configure":
      default:
        return drawerDraft.mapped ? (
          <span>
            Editing mapped model
            {" "}
            <strong>{selectedTable?.mappedModelDisplayName || selectedTable?.mappedModelSingularName}</strong>
            {drawerDraft.mappedModuleLabel ? ` in ${drawerDraft.mappedModuleLabel}` : ""}
          </span>
        ) : (
          <span>Configure the field mapping draft before generating the metadata JSON preview.</span>
        );
    }
  })() : null;

  return (
    <div className="sdix-page">
      {isBootstrapLoading ? (
        <div className="sdix-loading">
          <SolidSpinner size={28} />
          <p>Loading introspection workspace...</p>
        </div>
      ) : bootstrapError ? (
        <div className="sdix-error">
          <span>{readQueryError(bootstrapError)}</span>
          <SolidButton size="small" variant="outline" onClick={() => void refetchBootstrap()}>
            Retry
          </SolidButton>
        </div>
      ) : (
        <>
          {!isWorkspaceMode ? (
            <div className="sdix-toolbar">
              <div className="sdix-toolbar__left">
                <div className="sdix-toolbar-search">
                  <Search size={15} />
                  <SolidInput
                    value={tableSearch}
                    onChange={(event) => setTableSearch(event.target.value)}
                    placeholder="Search tables"
                    disabled={!selectedDatasource}
                  />
                </div>
              </div>

              <div className="sdix-toolbar__actions">
                {isBootstrapFetching || isTablesFetching ? (
                  <div className="sdix-inline-status">
                    <SolidSpinner size={16} />
                    <span>Refreshing</span>
                  </div>
                ) : null}
                <SolidButton
                  size="small"
                  leftIcon={<Sparkles size={14} />}
                  onClick={() => {
                    if (selectedListRow) {
                      startMappingForRecord(selectedListRow);
                    }
                  }}
                  disabled={!selectedListRow}
                >
                  Start Mapping
                </SolidButton>
                <SolidSelect
                  value={selectedDatasource}
                  options={datasourceOptions}
                  placeholder="Datasource"
                  className="sdix-toolbar-select sdix-toolbar-select--compact"
                  onChange={(event) => setSelectedDatasource(event.value)}
                />
                <SolidButton
                  size="small"
                  className="sdix-icon-button"
                  leftIcon={<RefreshCw size={16} />}
                  onClick={() => void handleRefresh()}
                  tooltip="Refresh"
                  aria-label="Refresh"
                />
                <SolidButton
                  size="small"
                  className="sdix-icon-button"
                  leftIcon={<Cog size={16} />}
                  onClick={() => {
                    setDraftSessionSettings(sessionSettings);
                    setSettingsTab("datasource-info");
                    setSettingsOpen(true);
                  }}
                  tooltip="Session settings"
                  aria-label="Session settings"
                />
              </div>
            </div>
          ) : null}

          {selectedDatasource && tablesResponse?.synchronizeBlocked ? (
            <div className="sdix-blocker">
              <ShieldAlert size={20} />
              <div>
                <h3>Synchronize must be disabled before introspection</h3>
                <p>{tablesResponse.synchronizeMessage}</p>
              </div>
            </div>
          ) : null}

          {!isWorkspaceMode ? (
            <div className="sdix-workbench">
              <div className="sdix-table-shell">
                {!selectedDatasource ? (
                  <div className="sdix-empty-state is-inline">
                    <Database size={22} />
                    <p>Select a datasource to load its tables.</p>
                  </div>
                ) : isTablesLoading ? (
                  <div className="sdix-loading is-inline">
                    <SolidSpinner size={24} />
                    <p>Inspecting datasource tables...</p>
                  </div>
                ) : tablesError ? (
                  <div className="sdix-error is-inline">
                    <span>{readQueryError(tablesError)}</span>
                    <SolidButton size="small" variant="outline" onClick={() => void refetchTables()}>
                      Retry
                    </SolidButton>
                  </div>
                ) : !filteredRecords.length ? (
                  <div className="sdix-empty-state is-inline">
                    <Database size={22} />
                    <p>{tableSearch ? "No tables match the current quick filter." : "No database tables were discovered for this datasource."}</p>
                  </div>
                ) : (
                  <div className="sdix-table-area">
                    <SolidDataTable
                      value={filteredRecords}
                      dataKey="tableName"
                      viewportHeight="calc(100vh - 162px)"
                      size="small"
                      onRowClick={({ data }) => setSelectedRows([data])}
                      rowClassName={(rowData) => `${rowData.schema ?? ""}::${rowData.tableName}` === selectedListRowKey ? "sdix-table-row-selected" : ""}
                      emptyMessage="No datasource tables found"
                    >
                      <Column
                        header=""
                        body={(rowData: DatasourceIntrospectionTableRecord) => {
                          const rowKey = `${rowData.schema ?? ""}::${rowData.tableName}`;
                          return (
                            <div className="sdix-selection-cell" data-no-row-click="true">
                              <SolidCheckbox
                                checked={rowKey === selectedListRowKey}
                                onChange={(event) => setSelectedRows(event.target.checked ? [rowData] : [])}
                              />
                            </div>
                          );
                        }}
                        style={{ width: 52, minWidth: 52 }}
                      />
                      <Column
                        field="tableName"
                        header="Table"
                        body={(rowData: DatasourceIntrospectionTableRecord) => (
                          <div className="sdix-table-primary-cell">
                            <strong>{rowData.tableName}</strong>
                          </div>
                        )}
                        style={{ minWidth: 240 }}
                      />
                      <Column field="schema" header="Schema" body={(rowData: DatasourceIntrospectionTableRecord) => rowData.schema || "dbo/default"} style={{ minWidth: 120 }} />
                      <Column
                        header="Status"
                        body={(rowData: DatasourceIntrospectionTableRecord) => (
                          <span
                            className={`sdix-status-badge ${rowData.mapped ? "is-mapped" : "is-unmapped"}`}
                          >
                            {statusLabel(rowData)}
                          </span>
                        )}
                        style={{ minWidth: 150 }}
                      />
                      <Column
                        header="Superclass"
                        body={(rowData: DatasourceIntrospectionTableRecord) => rowData.suggestedBaseClassName}
                        style={{ minWidth: 220 }}
                      />
                      <Column field="suggestedUserKeyField" header="User Key" style={{ minWidth: 160 }} />
                      <Column
                        header="Mapped Model"
                        body={(rowData: DatasourceIntrospectionTableRecord) => (
                          rowData.mapped
                            ? (
                              <div className="sdix-table-primary-cell">
                                <strong>{rowData.mappedModelDisplayName || rowData.mappedModelSingularName || "-"}</strong>
                                {rowData.mappedModuleDisplayName || rowData.mappedModuleName ? (
                                  <span>{rowData.mappedModuleDisplayName || rowData.mappedModuleName}</span>
                                ) : null}
                              </div>
                            )
                            : <span className="sdix-muted-cell">Not mapped</span>
                        )}
                        style={{ minWidth: 200 }}
                      />
                      <Column
                        header="System Columns"
                        body={(rowData: DatasourceIntrospectionTableRecord) => Math.max(rowData.columnCount - rowData.physicalColumnCount, 0)}
                        style={{ minWidth: 130 }}
                      />
                      <Column
                        header="Columns"
                        body={(rowData: DatasourceIntrospectionTableRecord) => rowData.physicalColumnCount}
                        style={{ minWidth: 110 }}
                      />
                    </SolidDataTable>
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="sdix-workspace-screen">
              <div className="sdix-workspace-header">
                <SolidButton size="small" variant="outline" leftIcon={<ArrowLeft size={14} />} onClick={leaveWorkspace}>
                  Back
                </SolidButton>
                <div className="sdix-workspace-header__identity sdix-workspace-header__identity--right">
                  <h2>{selectedTable?.tableName || "Mapping workspace"}</h2>
                  <p>
                    {selectedTable
                      ? `${selectedTable.schema || "dbo"} · ${selectedDatasourceRecord?.database || selectedDatasourceRecord?.displayName || "Datasource"}${selectedDatasourceRecord ? ` · ${providerLabel(selectedDatasourceRecord.type)}` : ""}`
                      : "Complete the legacy table mapping in a dedicated workspace."}
                  </p>
                </div>
              </div>

              {!selectedTable && !isTablesLoading ? (
                <div className="sdix-error">
                  <span>The selected table is no longer available for this datasource.</span>
                  <SolidButton size="small" variant="outline" onClick={leaveWorkspace}>
                    Back to table list
                  </SolidButton>
                </div>
              ) : drawerLoadingError ? (
                <div className="sdix-error">
                  <span>{readQueryError(drawerLoadingError)}</span>
                  <SolidButton size="small" variant="outline" onClick={() => void refetchTableDetail()}>
                    Retry
                  </SolidButton>
                </div>
              ) : isDrawerBlockingLoading ? (
                <div className="sdix-loading sdix-workspace-loading">
                  <SolidSpinner size={24} />
                  <p>Preparing column mapping preview...</p>
                </div>
              ) : (
                <div className="sdix-wizard-shell">
                  <div className="sdix-wizard-stepper">
                    {stepperItems.map((step, index) => (
                      <button
                        key={step.key}
                        type="button"
                        className={[
                          "sdix-wizard-stepper-item",
                          step.active ? "is-active" : "",
                          step.complete ? "is-complete" : "",
                          step.disabled ? "is-disabled" : "",
                        ].filter(Boolean).join(" ")}
                        onClick={step.onClick}
                        disabled={step.disabled}
                      >
                        <span className="sdix-wizard-stepper-badge">
                          {step.complete ? <Check size={12} /> : index + 1}
                        </span>
                        <span className="sdix-wizard-stepper-label">{step.label}</span>
                      </button>
                    ))}
                  </div>

                  <div className="sdix-wizard-panel">
                    <div className="sdix-wizard-panel__body">
                      {workspaceContent}
                    </div>
                  </div>

                  {drawerDraft ? (
                    <div className="sdix-wizard-footer">
                      <div className="sdix-wizard-footer__meta">{workspaceMeta}</div>
                      <div className="sdix-wizard-footer__actions">
                        {drawerDraft.mapped && drawerDraft.modelId ? (
                          <SolidButton size="small" variant="outline" leftIcon={<ExternalLink size={14} />} onClick={openMappedModelForm}>
                            Open model form
                          </SolidButton>
                        ) : null}
                        {workspaceStep === "configure" ? (
                          <SolidButton
                            size="small"
                            leftIcon={<Save size={14} />}
                            loading={isPreviewMappingLoading}
                            onClick={() => void reviewMappingJson()}
                          >
                            Review Mapping JSON
                          </SolidButton>
                        ) : null}
                        {workspaceStep === "review-json" ? (
                          <>
                            <SolidButton size="small" variant="outline" onClick={() => setWorkspaceStep("configure")}>
                              Back
                            </SolidButton>
                            <SolidButton size="small" leftIcon={<Save size={14} />} loading={isSavingMapping} onClick={() => void persistMappingArtifacts()}>
                              Save Mapping
                            </SolidButton>
                          </>
                        ) : null}
                        {workspaceStep === "generate-code" ? (
                          <>
                            <SolidButton size="small" variant="outline" onClick={() => setWorkspaceStep("review-json")}>
                              Back
                            </SolidButton>
                            <SolidButton
                              size="small"
                              disabled={!hasAttemptedGenerateCode || isGenerateCodeLoading || isGeneratingCodeWorkflow}
                              onClick={() => setWorkspaceStep("create-migrations")}
                            >
                              Continue
                            </SolidButton>
                          </>
                        ) : null}
                        {workspaceStep === "create-migrations" ? (
                          <>
                            <SolidButton size="small" variant="outline" onClick={() => setWorkspaceStep("generate-code")}>
                              Back
                            </SolidButton>
                            <SolidButton size="small" leftIcon={<Save size={14} />} loading={isCreatingMigrationArtifacts} onClick={() => void handleCreateMigrationArtifacts()}>
                              Create Migration Artifacts
                            </SolidButton>
                          </>
                        ) : null}
                        {workspaceStep === "run-migration" ? (
                          runMigrationCompleted ? (
                            <SolidButton
                              size="small"
                              leftIcon={<Check size={14} />}
                              onClick={() => navigate("/admin/core/solid-core/model-metadata/list")}
                            >
                              Finish
                            </SolidButton>
                          ) : (
                            <>
                              <SolidButton size="small" variant="outline" onClick={() => setWorkspaceStep("create-migrations")}>
                                Back
                              </SolidButton>
                              <SolidButton size="small" leftIcon={<Database size={14} />} loading={isRunMigrationLoading} onClick={() => void handleRunMigration()}>
                                Run Migration
                              </SolidButton>
                            </>
                          )
                        ) : null}
                      </div>
                    </div>
                  ) : null}
                </div>
              )}
            </div>
          )}

          <SolidDialog
            open={settingsOpen}
            onOpenChange={setSettingsOpen}
            style={{ width: "min(560px, calc(100vw - 32px))" }}
          >
            <SolidDialogHeader>
              <div>
                <SolidDialogTitle>Session settings</SolidDialogTitle>
                <SolidDialogDescription>
                  Review the selected datasource and adjust the session-specific introspection flags.
                </SolidDialogDescription>
              </div>
              <SolidDialogClose />
            </SolidDialogHeader>
            <SolidDialogSeparator />
            <SolidDialogBody>
              <SolidTabGroup
                tabs={settingsTabs}
                value={settingsTab}
                onValueChange={setSettingsTab}
                className="sdix-settings-tabs"
                panelClassName="sdix-settings-tab-panel"
              />
            </SolidDialogBody>
            <SolidDialogFooter>
              <SolidButton variant="outline" onClick={() => setSettingsOpen(false)}>
                Cancel
              </SolidButton>
              <SolidButton onClick={applyDraftSettings}>
                Apply
              </SolidButton>
            </SolidDialogFooter>
          </SolidDialog>
        </>
      )}
    </div>
  );
}
